name:  RDP-Helper

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest


    env:
      Solution_Path: RDP-Helper.sln
      PublishFile: 'bin\publish\RDP-Helper.exe'
      Wpf_Project_Path: RDP-Helper.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.


    - name: Use Nerdbank.GitVersioning to set version variables
      uses: dotnet/nbgv@master
      id: nbgv


    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'


    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
        
        
    - name: Build
      run: msbuild $env:Solution_Path /t:Restore /t:publish /p:Platform="Any CPU"
        /p:Configuration=Release /p:PublishProfile="Properties\PublishProfiles\single.pubxml"
        
    - name: FileScan
      shell: pwsh
      run: ls bin\
 
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        shell: pwsh
        tag_name: $(Get-Date -Format "yyyyMMdd-HHmm")
        name: RDP-Helper
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        body: | 
          Release Note:
          - fix: Several small issues
          - date:  $(Get-Date -Format "yyyy-MM-dd-HH:mm")
        files: | 
          ${{ env.PublishFile }}
